### ISSUE TITLE
select2 not loading on multi-select field

### ISSUE THREAD

**Issue by jackmcconnell** [game-ryo/acf-multiple-taxonomy#2]
This is a great plugin and fills a gap where ACF falls slightly short. 

I've converted an exisiting taxonomy field to a new multi-select taxonomy field, added by your plugin. 
Only issue is that select2 doesn't appear to be loading on the multi-select field when editing it, which makes it hard to select fields in a user-friendly way. Have tested with other plugins deactivated and checked the console but no errors or issues show. I think this is a bug but would be good to see if you can replicate it.

**Comment by dentugov** [comment]
I'm joining you. Unfortunately, there is such a problem

**Comment by game-ryo** [comment]
My apologies. I should have noticed your report.

Is the Stylized UI option enabled?
The search box appears on the selection only when this option is turned on.
If the problem still occurs even with the Stylized UI option turned on, please provide detailed steps to reproduce the problem.

**Comment by jackmcconnell** [comment]
No probs. I don't have access to the site where the issue occurred anymore so couldn't test to see if the Stylized UI option was enabled or not. I noticed the issue immediately after installing the plugin though. I don't think I did anything else other than change the original Taxonomy field to the multi-select Taxonomy field that your plugin provides and noticed the issue straight away.

**Comment by game-ryo** [comment]
Ok, I understand.
I will remove the Stylized UI toggle in the next update and always enable it.
I am sure many people are encountering the same problem.
Thank you very much.

**Comment by game-ryo** [comment]
The Stylized UI toggle has been removed in today's update (ver. 1.0.6).
This option is now always on.
