### ISSUE TITLE
The plugin no longer works after ACF 6.3.2

### ISSUE THREAD

**Issue by justinmaurerdotdev** [game-ryo/acf-multiple-taxonomy#4]
The fields made by this plugin no longer have valid nonces. There are consistently no results, and I have confirmed that it's returning an empty response because it is failing the `acf_verify_ajax()` check.

Here's what it looks like:
<img width="1267" alt="Screenshot 2024-07-10 at 4 50 36 PM" src="https://github.com/game-ryo/acf-multiple-taxonomy/assets/3308529/04d636f2-bb42-4fe4-9ce3-8b8d5b70b5b2">

According to the [changelog](https://www.advancedcustomfields.com/changelog/), there were A LOT of changes made to the AJAX system in the latest versions (especially 6.3.2). I believe each field now requires its own nonce. I'm not familiar enough with either library to contribute a fix at this time. However, I am pretty familiar with AJAX in WordPress, so I'd be happy to help write new code if the exact problem with ACT Multiple Taxonomy were identified.

**Comment by game-ryo** [comment]
This issue has been resolved with a contribution from justinmaurerdotdev.
